favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.4983137
  brandStrength: 0.8743676
  lightness: 0.4915683
  brandColors:
    - '#ffffff'
    - '#d29426'
    - '#e6c47a'
    - '#ae5904'
    - '#d9a580'
  rhythmicContrast: 0.4932546
typography_spectrum: 0.08538
layout_spectrum: 0.64997
cta:
  bucket: null
  version: null
  domain: null
name: Cookbook
