name: Umami Studio
favicon: null
layout_spectrum: 0.85347
typography_spectrum: 0.5197133
title: Umami Studio
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-79217923-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080f18'
    - '#00fbf5'
    - '#0063ce'
    - '#f6faf8'
    - '#9a8c65'
  brandStrength: 0.0625
  lightness: 0.4915683
  saturation: 0.4983137
  rhythmicContrast: 0.4932546
purpose: []
