name: Cookbook
favicon: null
layout_spectrum: 0.1819273098371923
typography_spectrum: 0.2088862748350948
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8704426179174334
  lightness: 0.5648996334057301
  saturation: 0.5805499504785985
  rhythmicContrast: 0.28979642828926444
purpose: []
