title: Umami Studio
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4983137
  brandStrength: 0.0625
  rhythmicContrast: 0.4932546
  brandColors:
    - '#080f18'
    - '#00fbf5'
    - '#0063ce'
    - '#f6faf8'
    - '#9a8c65'
  lightness: 0.4915683
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Umami Studio
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5197133
layout_spectrum: 0.85347
