name: Cookbook
favicon: null
layout_spectrum: 0.1819273098371923
typography_spectrum: 0.08538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d29426'
    - '#e6c47a'
    - '#ae5904'
    - '#d9a580'
  brandStrength: 0.5
  lightness: 0.5648996334057301
  saturation: 0.5805499504785985
  rhythmicContrast: 0.28979642828926444
purpose: []
