name: Cookbook
favicon: null
layout_spectrum: 0.64997
typography_spectrum: 0.08538
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d29426'
    - '#e6c47a'
    - '#ae5904'
    - '#d9a580'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
