name: Umami Studio
favicon: null
layout_spectrum: 0.85347
typography_spectrum: 0.08538
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Umami Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00001c'
    - '#6a4d63'
    - '#eaebc9'
    - '#aeca75'
    - '#927f85'
  brandStrength: 0.125
  lightness: 0.4915683
  saturation: 0.4983137
  rhythmicContrast: 0.4932546
purpose: []
