favicon: null
cta:
  bucket: null
  version: null
  domain: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.886172
  brandStrength: 0.8743676
  lightness: 0.9013491
  brandColors:
    - '#ffffff'
    - '#d29426'
    - '#e6c47a'
    - '#ae5904'
    - '#d9a580'
  rhythmicContrast: 0.75
typography_spectrum: 0.08538
layout_spectrum: 0.64997
analytics:
  twitter: null
  google: null
  facebook: null
name: Cookbook
